outputs:
  keyboard:
    name: virtual-keyboard
    type: keyboard
  touchscreen:
    name: virtual-touchscreen
    type: touchscreen
  mouse:
    name: virtual-mouse
    type: mouse
  gamepad:
    name: virtual-gamepad
    type: gamepad

inputs:
  sunshine_keyboard:
    uniq: Sunshine Keyboard
    name: Keyboard passthrough
    product: 0xdead
    vendor: 0xbeef
  sunshine_mouse:
    uniq: Sunshine Mouse
    name: Logitech Wireless Mouse PID:4038
    product: 0x4038
    vendor: 0x46d
  sunshine_touch:
    uniq: Sunshine Touch
    name: Touchscreen passthrough
    product: 0xdead
    vendor: 0xbeef
  sunshine_gamepad:
    uniq: Sunshine Gamepad
    name: Microsoft X-Box 360 pad
    product: 0x28E
    vendor: 0x45E

mappings:
  - input: sunshine_keyboard
    output: keyboard
  - input: sunshine_mouse
    output: mouse
  - input: sunshine_gamepad
    output: gamepad
  - input: sunshine_touch
    output: touchscreen
